In [13]:
import pandas as pd

df_names = pd.read_csv('../data/smog1.csv')

### Data frame description

In [14]:
df_names.shape

(1646, 12)

### First 5 Data frame entries

In [15]:
df_names.head(5)

,NAME,STREET,POST_CODE,CITY,LONGITUDE,LATITUDE,HUMIDITY_AVG,PRESSURE_AVG,TEMPERATURE_AVG,PM10_AVG,PM25_AVG,TIMESTAMP
0,SZKO?A PODSTAWOWA IM. MARIANA FALSKIEGO W KRAS...,UL. SZKOLNA,63-522,KRASZEWICE,18.224030,51.515630,99.900000,1016.266667,18.633333,4.10,2.286667,2026-06-30 05:00:00.0
1,SZKO?A PODSTAWOWA WE WRZ?SOWICACH,UL. SZKOLNA,32-040,WRZ?SOWICE,19.942820,49.961030,70.381818,982.572727,23.463636,12.50,11.181818,2026-06-30 05:00:00.0
2,ZESP?? SZK?? NR 1 W PSZCZYNIE,UL. KAZIMIERZA WIELKIEGO,43-200,PSZCZYNA,18.945706,49.965883,99.900000,1005.350000,20.300000,27.65,17.495000,2026-06-30 05:00:00.0
3,ZESP?? SZK?? IM. POWSTA?C?W WIELKOPOLSKICH W J...,SZKOLNA,63-421,JANK?W PRZYGODZKI,17.788907,51.596172,99.900000,992.400000,16.400000,21.30,11.150000,2026-06-30 05:00:00.0
4,SZKO?A PODSTAWOWA NR 7 IM. ?O?NIERZY WRZE?NIA ...,UL. M?CZENNIK?W O?WI?CIMSKICH,43-229,?WIKLICE,18.989839,49.971937,99.900000,990.750000,22.000000,20.90,12.060000,2026-06-30 05:00:00.0

### Last 5 Data frame entries

In [16]:
df_names.tail(5)

,NAME,STREET,POST_CODE,CITY,LONGITUDE,LATITUDE,HUMIDITY_AVG,PRESSURE_AVG,TEMPERATURE_AVG,PM10_AVG,PM25_AVG,TIMESTAMP
1641,SZKO?A PODSTAWOWA IM.BOHATER?W WRZE?NIA 1939R....,KONOPNICKIEJ,34-240,JORDAN?W,19.834938,49.653449,84.109091,963.645455,18.972727,15.245455,14.972727,2026-06-30 05:00:00.0
1642,PRZEDSZKOLE NR 10 W PIASECZNIE,NADARZY?SKA,05-500,PIASECZNO,21.017680,52.072370,71.100000,1009.166667,24.341667,8.075000,7.808333,2026-06-30 05:00:00.0
1643,SZKO?A PODSTAWOWA IM. JANA PAW?A II W WILCZKOWIE,UL. MIKO?AJA KOPERNIKA,55-020,WILCZK?W,16.989396,50.966512,84.066667,1004.050000,22.325000,8.900000,8.600000,2026-06-30 05:00:00.0
1644,PRZEDSZKOLE SAMORZ?DOWE W GOLI,NaN,63-800,GOLA,16.944640,51.870920,84.818182,1007.845455,20.227273,3.709091,3.709091,2026-06-30 05:00:00.0
1645,SPO?ECZNA SZKO?A PODSTAWOWA W GZACH,NaN,06-126,GZY,20.925636,52.744815,76.990909,1008.527273,21.036364,8.309091,8.063636,2026-06-30 05:00:00.0